version: '3.8'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5065:80"
      - "7005:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Http:/root/.aspnet/http:ro
    depends_on:
      - authservice
    networks:
      - mynetwork

  authservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "7778:80"
      - "5556:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Http:/root/.aspnet/http:ro
    depends_on:
      - redis
      - rabbitmq-server
      - mssql
    networks:
      - mynetwork

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  rabbitmq-server:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ default port for AMQP
      - "15672:15672"  # RabbitMQ Management UI port
    networks:
      - mynetwork

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dubem@007
    ports:
      - "1431:1433"
    networks:
      - mynetwork

networks:
  mynetwork:

